export type { FileSystemPort } from './lib/ports/file-system.port';
export type { ProjectScannerPort } from './lib/ports/project-scanner.port';
export type { ManifestWriterPort } from './lib/ports/manifest-writer.port';
export type { InventoryAnalyzerPort, AngularInventory, NestInventory } from './lib/ports/inventory-analyzer.port';
export type { InventoryWriterPort } from './lib/ports/inventory-writer.port';
export { ScanProjectUseCase, ScanError } from './lib/use-cases/scan-project.use-case';
export type { ScanProjectInput } from './lib/use-cases/scan-project.use-case';
export { AnalyzeProjectUseCase, AnalysisError } from './lib/use-cases/analyze-project.use-case';
export type { AnalyzeProjectInput } from './lib/use-cases/analyze-project.use-case';
export type { InventoryReaderPort } from './lib/ports/inventory-reader.port';
export type { RouteMapWriterPort } from './lib/ports/route-map-writer.port';
export { BuildRouteMapUseCase, RouteMapError } from './lib/use-cases/build-route-map.use-case';
export type { BuildRouteMapInput } from './lib/use-cases/build-route-map.use-case';
export type { RouteMapReaderPort } from './lib/ports/route-map-reader.port';
export type { TestSuiteWriterPort } from './lib/ports/test-suite-writer.port';
export { GenerateTestsUseCase, GenerateTestsError } from './lib/use-cases/generate-tests.use-case';
export type { GenerateTestsInput } from './lib/use-cases/generate-tests.use-case';
export type { AiEnricherPort, AiEnrichment, ErrorCaseSpec } from './lib/ports/ai-enricher.port';
export type { TestRunnerInput, TestRunnerPort } from './lib/ports/test-runner.port';
export type { ProcessManagerPort } from './lib/ports/process-manager.port';
export { RunTestsUseCase, RunTestsError } from './lib/use-cases/run-tests.use-case';
export type { RunTestsInput } from './lib/use-cases/run-tests.use-case';
export type { HtmlReportPort, ReportOptions } from './lib/ports/html-report.port';
export { ExportReportUseCase, ExportReportError } from './lib/use-cases/export-report.use-case';
export type { ExportReportInput } from './lib/use-cases/export-report.use-case';
